### ISSUE TITLE
Exception thrown with unplayed matches

### ISSUE THREAD

**Issue by iwolterstorff** [MadDoctor5813/VexElo#1]
Exception is thrown when user inputs tournament at which matches were cancelled or otherwise unplayed

Try: RE-VRC-16-0975

**Comment by ktrieu** [comment]
The issue is resolved now, pretty simple null check error. [I have a newer version of this in website form](https://github.com/MadDoctor5813/VexELO_Web), if you want to look at it. It takes into account the whole season instead of just one match. A live copy is available at [vex-elo-rankings.herokuapp.com](http://vex-elo-rankings.herokuapp.com), though it isn't always up to date yet.
